# Site settings
title: Atomic Chef
url: http://127.0.0.1:4000/
description: "Cooking up elemental knowledge with ingredients from the periodic table."
baseurl: 

# Build settings
markdown: kramdown
permalink: pretty