# Site settings
title: Atomic Chef
email: hiya@email.com
url: http://127.0.0.1:4000/
description: "Cooking up elemental knowledge with ingredients from the periodic table."
baseurl:

# Footer settings
footer: Student | Copyright 2007

# Social network usernames
social:
    -   title: Instagram
        url: https://#
    -   title: Github
        url: https://#
    -   title: Twitter
        url: https://#

# Build settings
markdown: kramdown
permalink: pretty